---
groups:
- name: example
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: InstanceDown
    expr: up == 0
    for: 3s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  # Alert for any instance that has a median request latency >1s.
  - alert: Shard limits to low
    expr: wbx_catalog_storage_limit - wbx_catalog_storage_size < 300
    #for: 1m
    annotations:
      summary: "Shard capacity to low {{ $labels.instance }}"
      description: "Shard {{ $labels.instance }} have to much ordered len (limit will be reached in:{{ $value }} active products)"

