{
 "title": "Catalog DashB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Catalog free ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "wbx_catalog_storage_limit - wbx_catalog_storage_size"
    }
   ]
  },
  {
   "title": "Catalog limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "wbx_catalog_storage_limit" }
   ]
  },
  {
   "title": "Catalog used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "wbx_catalog_storage_size" }
   ]
  }
 ]
}